wandb_version: 1

noise_factor:
  desc: null
  value: 0
architecture:
  desc: null
  value: ResNet50
dataset:
  desc: null
  value: MNIST
epochs:
  desc: null
  value: 1000
batch_size:
  desc: null
  value: 64
learning_rate:
  desc: null
  value: 0.001
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719674859.719719
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      3:
      - 2
      - 16
      - 23
      4: 3.9.18
      5: 0.15.12
      6: 4.32.1
      8:
      - 3
      - 5
      13: windows-amd64
